### PR TITLE
Egress block port list

### PR DESCRIPTION
**Pull request by SathishKumarTR-Dell**
Added attribute to set an egress block list on a port.
Use-case is to achieve port isolation by preventing an ingress port from sending packets to a set of egress ports.

### CODE REVIEW

**Comment by lguohan** [comment]
thanks

**Comment by atitjain** [comment]
Hi Sathish,

What use case we are looking @ here.

**Comment by SathishKumarTR-Dell** [comment]
This can be used for port security like blocking a specific port from forwarding packets to certain other port(s). Can also be used to block the flooded packets in a network topology having redundant links like the Multichassis LAG.

**Comment by atitjain** [comment]
Just a thought, in the more networks moving to virtualized shouldn't we be thinking for port,vlan option rather than the port alone. Also for LAG on the egress how do we decide @ ingress port.

**Pull request closed without merging**
